# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: krisawatson
  tag: 1.0.0
  pullPolicy: Always
service:
  name: document-service
  type: ClusterIP
  externalPort: 8003
  internalPort: 8003
  version: 1
statefulset:
  version: 1
storage:
  className: standard
  mountName: storage
  path: /tmp/storage
volume:
  dbPropPath: /etc/properties
  dbPropFile: doc-db.properties
