server:
  port: 8003
  servlet:
    context-path: "/doc/v1"

logging:
  level:
    com.watsonsoftware: INFO

management.endpoints.web.exposure.include: "*"

spring:
  application:
    name: document-service
    release: doc-dev
  servlet.multipart:
    max-file-size: -1
    max-request-size: -1
