kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.storage.claimName }}
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.claimSize }}
