apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-{{ .Values.statefulset.version }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ .Chart.Name }}-{{ .Values.service.version }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/{{ .Values.service.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: http
        env:
        - name: DOC_DB_PROPERTIES
          value: file:{{ .Values.volume.dbPropPath}}/{{ .Values.volume.dbPropFile}}
        volumeMounts:
        - name: {{ .Values.storage.mountName }}
          mountPath: {{ .Values.storage.path }}
        - name: doc-db-properties
          mountPath: {{ .Values.volume.dbPropPath}}
      volumes:
      - name: doc-db-properties
        secret:
          secretName: doc-db-properties
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.storage.mountName}}
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.storage.className }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
