apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-{{ .Values.statefulset.version }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ .Chart.Name }}-{{ .Values.service.version }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/{{ .Values.service.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: http
        livenessProbe:
          httpGet:
            path: /doc/v1/actuator/health
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /doc/v1/actuator/health
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        env:
        - name: DOC_DB_PROPERTIES
          value: file:{{ .Values.volume.dbPropPath}}/{{ .Values.volume.dbPropFile}}
        - name: STORAGE
          value: {{ .Values.storage.path }}
        volumeMounts:
        - name: {{ .Values.storage.mountName }}
          mountPath: {{ .Values.storage.path }}
        - name: doc-db-properties
          mountPath: {{ .Values.volume.dbPropPath}}
      volumes:
      - name: doc-db-properties
        secret:
          secretName: doc-db-properties
      - name: {{ .Values.storage.mountName }}
        persistentVolumeClaim:
          claimName: {{ .Values.storage.claimName }}
  # volumeClaimTemplates:
  # - metadata:
  #     name: {{ .Values.storage.mountName}}
  #     annotations:
  #       volume.beta.kubernetes.io/storage-class: {{ .Values.storage.className }}
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
